version: "3.7"

services:
  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mariadb
      - app

  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ../database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build: ../
    ports: 
      - 5000:5000
    volumes: 
      - ../app:/code
    environment: 
      FLASK_APP: main.py
      FLASK_ENV: production
      FLASK_DEBUG: 0
      FLASK_SECRET_KEY: stress_test
      PYTHONUNBUFFERED: 1
      MYSQL_HOST: docker_mariadb_1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on: 
      - mariadb